/**
 * Data models for AdCrafter AI as specified in the PRD
 */

// User model
export interface User {
  userId: string;
  email: string;
  subscriptionTier: 'free' | 'basic' | 'pro';
  paymentDetails?: PaymentDetails;
  createdAt: string;
  updatedAt: string;
}

// Payment details for user
export interface PaymentDetails {
  customerId: string;
  defaultPaymentMethodId?: string;
  billingAddress?: BillingAddress;
}

export interface BillingAddress {
  line1: string;
  line2?: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
}

// Campaign model
export interface Campaign {
  campaignId: string;
  userId: string;
  name: string;
  niche: string;
  targetAudience: string;
  budget: number;
  spent: number;
  startDate: string;
  endDate: string;
  status: 'draft' | 'active' | 'paused' | 'completed';
  generatedBrief?: CampaignBrief;
  createdAt: string;
  updatedAt: string;
}

// Campaign brief generated by AI
export interface CampaignBrief {
  title: string;
  sections: {
    title: string;
    content: string;
  }[];
  createdAt: string;
}

// Influencer model
export interface Influencer {
  influencerId: string;
  name: string;
  username: string;
  niche: string;
  platform: 'instagram' | 'youtube' | 'tiktok' | 'twitter';
  followerCount: number;
  engagementRate: number;
  contactInfo: string;
  location: string;
  bio: string;
  avatar: string;
  priceRange: string;
  rating: number;
  campaignId?: string;
  createdAt: string;
  updatedAt: string;
}

// Performance metric model
export interface PerformanceMetric {
  metricId: string;
  campaignId: string;
  influencerId?: string;
  metricName: 'reach' | 'engagement' | 'clicks' | 'conversions' | 'revenue';
  value: number;
  timestamp: string;
}

// Subscription plan
export interface SubscriptionPlan {
  id: string;
  name: string;
  price: number;
  interval: 'month' | 'year';
  features: string[];
  campaignsLimit: number;
  analyticsLevel: 'basic' | 'advanced';
}

// Workflow model for automated campaign management
export interface Workflow {
  workflowId: string;
  campaignId: string;
  name: string;
  type: 'outreach' | 'communication' | 'payment';
  steps: WorkflowStep[];
  status: 'active' | 'paused' | 'completed';
  createdAt: string;
  updatedAt: string;
}

export interface WorkflowStep {
  stepId: string;
  workflowId: string;
  name: string;
  type: 'email' | 'notification' | 'task' | 'payment';
  config: Record<string, any>;
  status: 'pending' | 'completed' | 'failed';
  order: number;
}

// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: {
    message: string;
    code?: string;
  };
}

